import type { Metadata } from "next";
import { notFound } from "next/navigation";
import localFont from "next/font/local";
import "./globals.css";

import ErrorBoundary from "@/components/layout/ErrorBoundary";
import Nav from "@/components/layout/Nav";
import Footer from "@/components/layout/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface NavItem {
  label: string;
  type: "link" | "dropdown";
  link?: { slug: string };
  dropdownItems?: Array<{ label: string; link: { slug: string } }>;
}

interface NavigationData {
  items: NavItem[];
}

interface BrandData {
  companyLogo: {
    url: string;
  };
  brandColors: {
    primary: string;
    secondary: string;
  };
  socialLinks: {
    facebook: string;
    instagram: string;
    twitter: string;
    linkedin: string;
  };
}

const defaultNavigation: NavigationData = { items: [] };
const defaultBrand: BrandData = {
  companyLogo: { url: "" },
  brandColors: { primary: "", secondary: "" },
  socialLinks: { facebook: "", instagram: "", twitter: "", linkedin: "" },
};

async function getNavigation(): Promise<NavigationData> {
  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_PAYLOAD_URL}/api/globals/main-navigation`,
      { next: { revalidate: 60 } }
    );
    if (!res.ok) {
      throw new Error("Failed to fetch navigation data");
    }
    return res.json();
  } catch (error) {
    console.error(error);
    return defaultNavigation;
  }
}

async function getBrandData(): Promise<BrandData> {
  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_PAYLOAD_URL}/api/globals/brand`,
      { next: { revalidate: 60 } }
    );
    if (!res.ok) {
      throw new Error("Failed to fetch global config data");
    }
    return res.json();
  } catch (error) {
    console.error(error);
    return defaultBrand;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigation = await getNavigation();
  const brand = await getBrandData();

  if (!brand || !navigation) return notFound();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorBoundary>
          <header>
            <Nav items={navigation?.items} logo={brand?.companyLogo?.url} />
          </header>
          {children}
          <Footer brand={brand} />
        </ErrorBoundary>
      </body>
    </html>
  );
}
