import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Nav from "@/components/layout/Nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface NavItem {
  label: string;
  type: "link" | "dropdown";
  link?: { slug: string };
  dropdownItems?: Array<{ label: string; link: { slug: string } }>;
}

interface NavigationData {
  items: NavItem[];
}

async function getNavigation(): Promise<NavigationData> {
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_PAYLOAD_URL}/api/globals/main-navigation`,
    { next: { revalidate: 60 } }
  );
  if (!res.ok) {
    throw new Error("Failed to fetch navigation data");
  }
  return res.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navigation = await getNavigation();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Nav items={navigation.items} />
        </header>
        {children}
      </body>
    </html>
  );
}
